image: node:12

stages:
  - deploy

deploy:
  stage: deploy
  # when: manual
  only:
    - master
  # dependencies:
  #   - build
  image: ubuntu
  # before_script:
  #   # Setup SSH
  #   - echo 'Start before_script'
  #   - echo 'SSH setup...'
  #   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  #   - mkdir -p ~/.ssh
  #   - chmod 700 ~/.ssh

  #   # Append keyscan output into known hosts
  #   - echo 'Adding known hosts to known_hosts file...'
  #   - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  #   - chmod 644 ~/.ssh/known_hosts

  #   # Inject the remote's private key
  #   - echo 'Initializing ssh-agent...'
  #   - eval "$(ssh-agent)"

  #   - echo 'Injecting the remotes private key...'
  #   - echo "$SSH_PRIVATE_KEY"
  #   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  script:
    - echo 'Start script'
    - apt-get update -y
    - 'which ssh-agent || (apt-get install openssh-client -y)'
    - apt-get install sshpass -y
    - which ssh
    - which sshpass
    - sshpass -p "${VPS_PASSWORD}" ssh ${VPS_USER}@${VPS_IP_ADDRESS} 'df -h'
