image: node:12

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  only:
    - master
  # dependencies:
  #   - build
  image: ubuntu
  script:
    - apt-get update -y
    - 'which ssh-agent || (apt-get install openssh-client -y)'
    - apt-get install sshpass -y
    - which ssh
    - which sshpass
    - sshpass -p "${VPS_PASSWORD}" ssh sblue@165.22.167.150 "df -h"
