image: node:12

stages:
  - build
  - deploy

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install -g @nrwl/cli
    - npm install -g @angular/cli
    - npm install -g ng-tailwindcss
    - npm install
    - ngtw build
    - npm run build wx-frontend
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package-lock.json
      - package.json
      - angular.json
      - nx.json
      - ng-tailwind.js

deploy:
  stage: deploy
  when: manual
  only:
    - master
  script:
    # Inject the remote's private key
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    # Append keyscan output into known hosts
    - ssh-keyscan $VPS_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy code via rsync
    - rsync -avuz --exclude=".*" $CI_PROJECT_DIR $VPS_USER@$VPS_IP_ADDRESS:~

    # Non interactive ssh gracefully reloads server
    - ssh $VPS_USER@$VPS_IP_ADDRESS '. /etc/profile; pm2 reload all'
