image: node:12

stages:
  - build

deploy:
  stage: deploy
  when: manual
  only:
    - master
  dependencies:
    - build
  image: ubuntu
  script:
    - sudo apt-get update
    - sudo apt-get install sshpass -y
    - sudo sshpass  -p ${VPS_PASSWORD} -v ssh -o StrictHostKeyChecking=no ${VPS_USER}@${VPS_IP_ADDRESS} 'mkdir /var/www/test-ci'
