image: node:12

stages:
  - build
  - deploy

cache:
  key: '${CI_COMMIT_REF_SLUG}'
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install -g typescript @nrwl/cli @angular/cli ng-tailwindcss
    - npm install
    - npm run build:wx-frontend
    - npm run build:wx-backend
    - npm run build:wx-backend-cron
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package-lock.json
      - package.json
      - angular.json
      - nx.json
      - ng-tailwind.js

deploy:
  stage: deploy
  when: manual
  only:
    - master
  dependencies:
    - build
  image: ubuntu
  before_script:
    # Inject the remote's private key
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval "$(ssh-agent)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    # Append keyscan output into known hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # - ssh-keyscan $VPS_IP_ADDRESS >> ~/.ssh/known_hosts
    # - chmod 644 ~/.ssh/known_hosts
  script:
    # Deploy code via rsync
    - rsync -avuz --exclude=".*" $CI_PROJECT_DIR $VPS_USER@$VPS_IP_ADDRESS:/var/www/wx/

    # Non interactive ssh gracefully reloads server
    - ssh $VPS_USER@$VPS_IP_ADDRESS '. /etc/profile; pm2 reload all'
