image: node:12

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  only:
    - master
  # dependencies:
  #   - build
  image: ubuntu
  script:
    - apt-get update
    - apt-get install sshpass -y
    - sshpass -p ${VPS_PASSWORD} ssh ${VPS_USER}@${VPS_IP_ADDRESS} 'mkdir /var/www/test-ci'
