name: Snow depth cron

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Cron job
    runs-on: ubuntu-latest
    steps:
      - name: 'Run snow depth job'
        run: curl -X POST https://knowyoursnow.com/api/snow/depth
